version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu
hooks:
  ApplicationStart:
    - location: scripts/start_hive
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_hive
      timeout: 300
      runas: root

