version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_cortex
      timeout: 300
      runas: root


